### ISSUE TITLE
Table contents checking

### ISSUE THREAD

**Issue by zubkov-andrei** [rjuju/pg_validate_extupgrade#3]
Hello, Julien!

I have an idea of a feature for _pg_validate_extupgrade_.
Contents of some tables in my extension is used to store version-dependent queries. DML on those tables is a part of upgrade script. I think there is a couple of cases, when contents of some extension tables will be version-dependent.
It wold be nice to specify names of such tables to _pg_validate_extupgrade_ for content checking. I think, table contents might be the same with except of column order.

**Comment by rjuju** [comment]
Hello Andrei,

Indeed I was wondering if there would be a need to validate some data on top of the objects structure.

I'll be happy to add such a feature.  I'm not sure what the best way to specify that.  Sure adding a list of tables could work, but it needs explicit user action and may require extra argument if some rows should be discarded.

I'm wondering if we could make use of the `pg_extension_config_dump()` calls in some way?  Maybe always checking all tables that configured to be dump with a predicate, and only check for the rows that match the predicate, since those should always be the autogenerated data.

It might not cover all use cases though, so we should need a way to specify additional tables.  A primary key should also exists on the tables to be checked to be able to find differences.

I'm also wondering if some columns should be discarded.  Maybe in some cases you'll have unstable data in some of the columns (like a timestamp, an uuid...).  It therefore raise a concern of what to do if the unstable columns are part of the primary key.

> except of column order.

Note that the tool will raise a problem if the columns order did change.  In theory it shouldn't be a problem, but given the possibility of having users relying on plain "SELECT *" rather than explicitly naming the wanted columns I chose a conservative approach.

**Comment by zubkov-andrei** [comment]
You are right - the general solution looks impossible without explicit user action.

Rely on `pg_extension_config_dump()` seems reasonable, but in this case we'll bump into unstable data for sure (at least in my case).

Maybe, the user could provide a set of queries to test? This won't convenient for user - it will looks like some kind of one more regression test executed by your tool, i think. But it will be pretty flexible.

**Comment by rjuju** [comment]
> Rely on pg_extension_config_dump() seems reasonable, but in this case we'll bump into unstable data for sure (at least in my case).

Ah, well that clearly shouldn't be the first option then.  Maybe a switch can be added for that, but we can see that later.

> Maybe, the user could provide a set of queries to test? This won't convenient for user - it will looks like some kind of one more regression test executed by your tool, i think. But it will be pretty flexible.

I'm fine with that, but it leaves the whole burden to extension developers to write something that will reliably work.  If they can only provides a query then I can only compare things by record number, which isn't the best way to diagnose discrepancies.  It would also be up to them to make sure that they queries always returns the rows in a stable order.  Maybe we could provide various approaches to compare the resultset?  Like per key (and you have to specify which columns), per row number...

I'm wondering if a good way to provide all of that would be to handle a configuration file.  Otherwise providing command line arguments will quickly become a mess, which will also be hard to reuse each time you need it.

**Comment by zubkov-andrei** [comment]
>  Maybe a switch can be added for that

This should be nice - most extensions do not store any historic data, so it would be a sort cut for them.

> I'm fine with that, but it leaves the whole burden to extension developers to write something that will reliably work.

Of course. But the whole feature of checking table contents won't be needed by anyone. Most extensions will be checked fine with _pg_validate_extupgrade_ base functionality. And for complicated cases we will have a complicated tests. At least, it would be the nice start point.

>  It would also be up to them to make sure that they queries always returns the rows in a stable order. Maybe we could provide various approaches to compare the resultset? Like per key (and you have to specify which columns), per row number...

Maybe. But I think, you shouldn't worry about that and we should do it as simple as possible. Like in regular regression tests - its extension developer responsibility to write a stable-resulting queries in them. I've made an effort to do this in my historic-oriented extension, so it looks quite possible to me.
Yes, this is not automatic way, but it seems to be simple to implement, and every extension developer who ever wrote an regression test will be familiar with such approach... And it is flexible... And, once again, it is extended functionality - only for quite complicated cases.

> I'm wondering if a good way to provide all of that would be to handle a configuration file. Otherwise providing command line arguments will quickly become a mess, which will also be hard to reuse each time you need it.

Of course, if there will be available several comparing approaches we can't handle it without complicated configuration file - there could be several queries with individual caparison conditions. But, if we'll use a regular regression test approach the folder with .sql files in an extension source will do the trick. We just need to pass this folder to _pg_validate_extupgrade_. However we need a way to specify an execution order...

**Comment by rjuju** [comment]
>  Like in regular regression tests - its extension developer responsibility to write a stable-resulting queries in them

Now that I think about it I did integrate a library to produce standard unified diff, so using the pg_regress approach should be easy to implement (assuming that rust-postgres has a way to transform a set of rows to a psql-like text output).

> However we need a way to specify an execution order...

I think that such queries should be read-only, so the execution order shouldn't be important as long as it's the same each time.  But in any case an array of string should be enough?

**Comment by zubkov-andrei** [comment]
> I think that such queries should be read-only, so the execution order shouldn't be important as long as it's the same each time.

Yes, right now I can't imagine the case, when we'll need to do a DML in those queries.. I think we even can take a single .sql file for testing. If it should be combined from several files, it can be done easily with _make_.

> But in any case an array of string should be enough?

I don't sure that I've understood correctly the place where that array should be implemented. Can you explain it a little bit detailed?

**Comment by rjuju** [comment]
> I don't sure that I've understood correctly the place where that array should be implemented. Can you explain it a little bit detailed

I was thinking of a configuration file.  Something like `pg_validate_extupgrade -p 5432 -c my_extension.config` with this file being something like:
```
host = "localhost"
extension: "my_extension"
from: "X"
to: "Y"
extra_queries: [
    "SELECT * FROM myextensiontable WHERE ... ORDER BY ...;",
    "SELECT ...",
]
``` 

If needed the option provided in the config file could also be overloaded by the one specified in the command line, so you can easily use the same config files against multiple postgres instances.

with a format to be determined.  I prefer an approach like that as there shouldn't be tons of validation queries.

**Comment by zubkov-andrei** [comment]
I've understand. I think this way is sufficient and might work. And it seems to be easier to implement than plain .sql file as it avoids queries separation.

**Comment by rjuju** [comment]
Great, I'll work on it soon!

**Comment by rjuju** [comment]
@zubkov-andrei I just pushed a new config_file branch at https://github.com/rjuju/pg_validate_extupgrade/commits/config_file.

It adds support for a new `-c | --config <configfile>` option.  Any option can be specified there, and will be overloaded if also specified on the command line.  For now the supported format are toml and json, and will be automatically detected using the file extension.  It would be trivial to add other format if you don't like any of of those.

You can also specify an `extra_queries` option (only in the config file), which is an array for the additional queries to be executed and which will be compared.  They will be executed sequentially in the order they are defined.

Note that there is not support for a psql-like output, so I manually generated an output format like:

```
field1: data1
field2: data2

field1: data3
field2: data4
[...]
```

hoping that the diffs will be more helpful than it were a single line per row output.

Also, since the output format is manual I only added support for a few postgres datatypes (bool, char, int, float, text...) for now.  This should be enough for most stable fields (which is why I didn't handle timestamp, time and such), but I can definitely add more if needed.  Notably I didn't add support for any array type.  Alternatively you can also manually cast the data to text in the query.

Let me know if there's any issue and if it's enough for you need!

**Comment by zubkov-andrei** [comment]
Thanks a lot Julien!

Data type limitations seems reasonable to me and as you mentioned we can do a manual cast in any complicated case.
I've tried it on my extension. It works as expected. This approach seems sufficient for most cases.

I was a little bit confused with two things:
- When _pg_validate_extupgrade_ detects a mismatch in an extra_query result, it emmits a message for me:
  ```
  - in extra_queries:
    installed and upgraded both have 1 Row but some mismatch in them:
  ```
  No matter how many rows are in the resultsets and how many are mismatched, I was always saw a "1 Row" here. It looks strange. If a row counting is difficult here, maybe we can omit it?
- If unsupported datatype is found in extra_query, error message `ERROR: Type timestamptz not handled` makes it difficult to find the exact statement in case when there are many of those.

**Comment by rjuju** [comment]
> I've tried it on my extension. It works as expected. This approach seems sufficient for most cases.

Good news!

> No matter how many rows are in the resultsets and how many are mismatched, I was always saw a "1 Row" here. It looks strange. If a row counting is difficult here, maybe we can omit it?

Ah indeed.  I'm reusing some generic infrastructure to compare stuff, and in the middle of the implementation I switched from per-row comparison to per result set comparison.  I think that comparing the whole result set will be way better than row per row.  Would it be ok if I rename it to "1 Resultset" instead?  It's still possible that one execution doesn't return anything while the other one does.

> If unsupported datatype is found in extra_query, error message ERROR: Type timestamptz not handled makes it difficult to find the exact statement in case when there are many of those.

That fair.  I'll try to improve this by adding the original query string and the column name!

**Comment by zubkov-andrei** [comment]
> Would it be ok if I rename it to "1 Resultset" instead? It's still possible that one execution doesn't return anything while the other one does.

The resultset comparison seems the only reasonable way to do this, but "1 Resultset" is also confusing. I think in trems of "empty / non-empty resultset" in this case.
About rows.. Is there a way to count rows during resultsets generation before comparison?

> I'll try to improve this by adding the original query string and the column name!

Thank you! I think this will be fine.

**Comment by rjuju** [comment]
> About rows.. Is there a way to count rows during resultsets generation before comparison?

I do see the number of rows at some point, but I don't save it anywhere for now.  That's a good point, I'll see if I can do that instead!

**Comment by rjuju** [comment]
@zubkov-andrei I just force pushed the changes.

If a datatype is not handled, here's what you will now get something like that:
```
ERROR: Type "timestamptz" for column "dt" not handled. Query:
SELECT now() as dt, 1 / (random() * 2)::int AS may_fail
```

And for the extra query diff, I added a diff-like information if the number of rows differ, and I changed the overall statement to "Resultset", to remind you how many queries were executed.  Not that you still get a resultset in case of error during execution, except that it will be considered as containing no rows (and have the error message as output).  I also made sure that execution could continue if there was an error here.

Here are some example of random failures with different scenarios:

```
  - in extra_queries:
    installed and upgraded both have 3 Resultset but some mismatch in them:
SELECT 1 / (random() * 2)::int AS may_fail
-- 1 rows
++ 0 rows

--- installed
+++ upgraded
@@ -1,2 +1,2 @@
-may_fail: 1
-
+Could not execute query:
+db error: ERROR: division by zero

SELECT 1, (random() * 1000)::int AS val FROM generate_series(1, (random() * 5)::int)
-- 3 rows
++ 2 rows

--- installed
+++ upgraded
@@ -1,9 +1,6 @@
 ?column?: 1
-val: 627
-
-?column?: 1
-val: 527
+val: 628

 ?column?: 1
-val: 323
+val: 662

SELECT name, version, installed, CASE installed WHEN true THEN random() ELSE NULL END AS rand FROM pg_available_extension_versions  WHERE name = 'pg_broken_extupgrade'
--- installed
+++ upgraded
@@ -26,5 +26,5 @@
 name: pg_broken_extupgrade
 version: head-1.1
 installed: true
-rand: 0.41066309010476587
+rand: 0.850806603619418
```

Let me know if I can improve anything!

**Comment by zubkov-andrei** [comment]
I think this is a very nice solution. I don't see any improvements right now.
_pg_validate_extupgrade_ is definitely very useful for quite big extensions (as in my case). Maybe I'll find something to improve.
Thanks a lot Julien!

**Comment by rjuju** [comment]
Thanks a lot Andrei, it was really helpful and your ideas are really great!

And I agree, I'm also maintaining extension with thousands of lines of code, it should make me more confident before publishing releases!

**Comment by zubkov-andrei** [comment]
Have a nice day!

**Comment by rjuju** [comment]
Thanks, you too!

(and I merged the branch in the master branch!)

**Comment by zubkov-andrei** [comment]
That is cool! I think it is time to describe a config file format in the docs now :)

**Comment by rjuju** [comment]
Indeed, thanks for the reminder!  I just added the documentation: https://github.com/rjuju/pg_validate_extupgrade#configuration-file
