### ISSUE TITLE
Extension relation comparison technique

### ISSUE THREAD

**Issue by zubkov-andrei** [rjuju/pg_validate_extupgrade#5]
Hi Julien!

Extension upgrade can contain columns addition to some tables. Those new columns obviously will be the last table attributes. But in the initial extension creation script of a new version they can appear in the middle of the table definition. Usually this improves readability.
In such cases table structures are considered different by _pg_validate_extupgrade_. From the database point of view such tables are different, but from relational theory point of view they are the same...

What do you think about sorting table attributes by name before comparison?
Of course we could bump into some `SELECT *` expressions used in an extension (however my opinion is that extension developers shouldn't do that).
Maybe comparison behavior could be configurable...

Best regards, Andrei

**Comment by rjuju** [comment]
Hi Andrei,

I thought about it but as you mentioned this won't play well with `SELECT *`.

But I think that unfortunately this problem is not only faced by the extension authors but also by all possible users of the extension.  As an extension author you have no guarantee that your users won't use such a `SELECT *` for their own purpose, so it seemed more important to validate that the scripts are truly idempotent and therefore don't have unreliable user-facing aspects.

I already faced that dilemma in some of my extension and chose to add the column at the end for both install and upgrade scripts, to make sure that my users won't face any problem depending on how they use the extension, even if that's not where I would have put the column if it was there initially.

Unfortunately, you can't even rely on view to fix that problem, as you would need to drop and recreate the view in the upgrade script and here again there's no guarantee that users won't also create views on top of it.

I'm afraid that making that behavior configurable will tend to reduce user experience (although it may help to raise awareness of the SELECT * antipattern).

**Comment by zubkov-andrei** [comment]
Thank you Julien! I'm agree this approach provides reliability to user experience. I think I need to do the same.
